"""Add deepwiki_task_id to AnalysisTask

Revision ID: 01e666a42462
Revises: e2d201fb732d
Create Date: 2025-12-03 08:56:39.158844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01e666a42462'
down_revision: Union[str, None] = 'e2d201fb732d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('deepwiki_task_id', sa.String(length=255), nullable=True, comment='DeepWiki文档生成任务ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'deepwiki_task_id')
    # ### end Alembic commands ###
